FROM python:2
ENV PYTHONUNBUFFERED 1  

EXPOSE 8080

RUN apt update
RUN apt install -y  nginx

RUN mkdir /src
WORKDIR /src
ADD . /src

RUN pip install -r requirements.txt
RUN cp /src/memeServer/settings-example.py /src/memeServer/settings.py

RUN ln -s /src/nginx-memes.conf /etc/nginx/sites-enabled/memes.conf
RUN service nginx restart
RUN chmod +X /src/web-startup.sh

CMD ["/bin/bash", "/src/web-startup.sh"]